# Generated by Django 5.2.3 on 2026-09-11 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='scans/')),
                ('label', models.CharField(choices=[('real', 'Real'), ('ai_generated', 'AI-generated')], max_length=20)),
                ('confidence', models.FloatField()),
                ('threshold_used', models.FloatField()),
                ('generator_attribution', models.CharField(blank=True, max_length=50, null=True)),
                ('explanation_text', models.JSONField(blank=True, null=True)),
                ('heatmap_image', models.ImageField(blank=True, null=True, upload_to='heatmaps/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='scans_scan_user_id_5deba4_idx')],
            },
        ),
    ]
