# Generated by Django 5.2.3 on 2026-09-11 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DegradationTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transform_type', models.CharField(max_length=30)),
                ('confidence_after', models.FloatField()),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='degradation_tests', to='scans.scan')),
            ],
        ),
    ]
