# Generated by Django 5.2.3 on 2026-09-14 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0002_degradationtest'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scan',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scan',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
